kind: Service
apiVersion: v1
metadata:
  name:  flask-app-service
  namespace: loco
spec:
  selector:
    app:  flask-app
  type:  LoadBalancer
  ports:
  - name:  flask-app-port
    port:  80
    targetPort:  80